baseURL = "https://anotherbug.com"
title = "鼠标土豆"
languageCode = "zh-cn"
DefaultContentLanguage = "zh-cn"
hasCJKLanguage = true 
theme = "mogege" 

paginate = 15 # 每页的文章数
enableEmoji = true # 支持 Emoji
enableRobotsTXT = true # 支持 robots.txt

[frontmatter]
date = [":filename", ":default"]
[permalinks]
posts = "/:year/:month/:day/:slug"

## 保持分类的原始名字（false会做转小写处理）
## preserveTaxonomyNames = true

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
  
  [[menu.main]]
    name = "好物"
    url = "/tools/"
    weight = 4
  
  [[menu.main]]
    name = "关于我"
    url = "/about/"
    weight = 5


[params]
    since = 2009
    author = "mousepotato"                          
    avatar = "assets/images/profile.jpg"        
    subtitle = "「人生最好的境界是丰富的安静」 — 周国平"                  
    home_mode = "" # post or other
    enableGitalk = false # gitalk 评论系统

    google_verification = ""

    description = "mousepotato 的个人博客" # (Meta) 描述
    keywords = "blog, Networking, Hugo, GNU/Linux, Linux, Ubuntu, Programming" # site keywords

    beian = ""
    baiduAnalytics = ""
    googleAnalytics = "UA-11501178-2" # Google 统计 id

    license= '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'
